instance_name  = "staging-vm"
machine_type   = "e2-standard-2"
zone           = "asia-south1-b"
region         = "asia-south1"
project_id     = "careful-relic-456115-n9"
image_family   = "debian-11"
image_project  = "debian-cloud"
